# Generated by Django 6.1 on 2026-08-28 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="astronomyshow",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="planetariumdome",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="showsession",
            options={"ordering": ["-show_time"]},
        ),
        migrations.AlterModelOptions(
            name="showtheme",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["row", "seat"]},
        ),
    ]
