# Generated by Django 6.1 on 2026-09-02 08:27

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_astronomyshow_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="astronomyshow",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=app.models.show_image_path
            ),
        ),
    ]
